### ISSUE TITLE
Add example for each alias in README.md

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/bash_utils#1]

**Comment by yashkathe** [comment]
I would like to contribute
Can i take up this issue ?

**Comment by Agrover112** [comment]
Sure @yashkathe

**Comment by Agrover112** [comment]
@yashkathe  go ahead

**Comment by yashkathe** [comment]
Actually running bash_aliases.sh gives me an error  

./bash_aliases.sh: line 25: syntax error: unexpected end of file

**Comment by Agrover112** [comment]
Try source fname.sh then source bashrc.sh

**Comment by yashkathe** [comment]
-bash: fname.sh: No such file or directory
-bash: bashrc.sh: No such file or directory

Still cant run the scripts
